[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#182c4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a202c"

[runner]
magicEnabled = true 